spring.application.name=Radegast

spring.datasource.url=jdbc:postgresql://localhost:5432/radegast
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
